name: Test
on:
  - pull_request
  - push
jobs:
  mix_test:
    name: mix test (Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.12.x'
            otp: '24.x'
          - elixir: '1.13.x'
            otp: '24.x'
          - elixir: '1.14.x'
            otp: '25.x'
          - elixir: '1.15.x'
            otp: '26.x'
          - elixir: '1.16.x'
            otp: '26.x'
    steps:
      - uses: actions/checkout@2036a08e25fa78bbd946711a407b529a0a1204bf # v2.3.2
      - uses: erlef/setup-beam@2f0cc07b4b9bea248ae098aba9e1a8a1de5ec24c # v1.17.5
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - name: Run tests
        run: mix test
